POST https://tcc-mr-gg.onrender.com/cursos
Content-Type: application/json

{
    "title": "Evandro",
    "description": "Esse é o nosso curso!",
    "professor":"Adilson",
    "duration": 180
}

###

GET https://tcc-mr-gg.onrender.com/cursos

###

PUT https://tcc-mr-gg.onrender.com/cursos/8
Content-Type: application/json

{
    cursos: [
    "title": "Tchesco",
    "description": "Esse é o nosso curso!",
    "professor":"tiline",
    "duration": 180
]}
###

DELETE https://tcc-mr-gg.onrender.com/cursos/6